### ISSUE TITLE
Does every crate need a homepage?

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-api-guidelines#26] opened 2017-04-04 23:56 UTC
The current guideline says:

> Cargo.toml includes all common headers (C-CARGO-HEADERS)
> \ authors, description, documentation, homepage, repository, readme, keywords, categories, license

Does something like [`lazy_static`](https://crates.io/crates/lazy_static) need a "homepage"? Here are two points of view:

- ### NO!

    The crates.io page already links to "repository" and "documentation." For something like lazy_static that should be all you need.

- ### YES!

    The "homepage" is the thing that we want people to link to when discussing a particular crate. For example in a blog post about Serde we would want them to link to https://serde.rs which is the homepage for Serde. We would not want them to link to crates.io or the repository or the rustdoc because those are not our preferred landing page for new users.

    Simpler crates like lazy_static should choose one of crates.io, repository, or rustdoc as their preferred landing page for new users and set that as the homepage.

**Comment by Razican** [comment] 2017-04-12 18:19
I think a crate should have a homepage if it actually have a homepage about it. Crates.io is not a homepage for any crate, it's a place where you can find crates. If you are already on the crate page, you don't need a link to itself. Rustdoc is documentation, and there is already a documentation keyword for it. And finally, GitHub is the repo, and you already have a keyword for it.

I have found myself clicking homepage in a crate thinking I would find a cool homepage, even a forum or some information about the crate and finally arriving to the GitHub repo in a repeated link.

So for my, the answer is no, lazy_static does not need a homepage. Nevertheless, if somebody creates a whole website about lazy_static, then it should be included in the TOML.

**Comment by brson** [comment] 2017-06-30 18:13
Add to existing guideline about crates.io metadata.

**Comment by brson** [comment] 2017-07-06 01:46
Let's only add 'homepage' when there's an actual homepage seperate from the doc and repo.

**Comment by lambda** [comment] 2017-07-07 15:29
I find it frustrating when crates list a homepage that is just a duplicate of the link to the docs or to the repository. It takes more time for me to explore to see where to find more information about the crate.

I think the guideline should be updated to explicitly mention this, and request removal of a redundant `homepage` link.

**Closed** 2017-07-18 05:50 UTC
Labels: important
